using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using Microsoft.EntityFrameworkCore.Metadata.Conventions.Infrastructure;

namespace Airtable.EFCore.Metadata.Conventions;

internal sealed class AirtableConventionSetBuilder : ProviderConventionSetBuilder
{
    public AirtableConventionSetBuilder(
        ProviderConventionSetBuilderDependencies dependencies,
        RelationalConventionSetBuilderDependencies relationalDependencies)
        : base(dependencies)
    {
        _relationalDependencies = relationalDependencies;
    }

    private readonly RelationalConventionSetBuilderDependencies _relationalDependencies;

    public override ConventionSet CreateConventionSet()
    {
        var set = base.CreateConventionSet();
        set.Add(new TableNameFromDbSetConvention(Dependencies));
        set.Add(new RelationalColumnAttributeConvention(Dependencies, _relationalDependencies));
        set.Add(new KeyShouldBeAutogeneratedConvention());
        set.Add(new TableNameAttributeConvention(Dependencies));
        set.Add(new SingleValueArrayConverterConvention(Dependencies));
        return set;
    }
}
